version: '3'

services:
  postgres:
    container_name: timescaledb_weather
    image: timescale/timescaledb-ha:pg15.5-ts2.12.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - weather_db:/home/postgres/pgdata/data

volumes:
  weather_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WEATHER_DB_PATH}
