version: '3'

services:
  postgres:
    container_name: ${CONTAINER_NAME}
    build: .
    image: ${IMAGE_NAME}:latest
    command: >
      postgres
      -c min_wal_size=4GB
      -c max_wal_size=16GB
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /storage6/:/storage6/
