version: '3'

services:
  postgres:
    container_name: timescaledb_weather
    image: timescale/timescaledb-ha:pg15.5-ts2.12.2
    command: >
      postgres
      -c min_wal_size=4GB
      -c max_wal_size=16GB
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - weather_db:/home/postgres/pgdata/data
      - /mnt/:/mnt/

volumes:
  weather_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WEATHER_DB_PATH}

# Just need this to bypass the VPN on some machines.
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
